### ISSUE TITLE
[client] model showing up for a fraction of a second after destroy

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#820] opened 2024-05-27 16:19 UTC
**seen on deployed version client**
when destroying a building you can see the building disappearing correctly. But then it comes back for a fraction of a second when the tx succeeds and then disappears again. Might be an issue with the optimistic destroy.

**Comment by edisontim** [comment] 2024-05-30 14:40
Fixed with #837, not the cleanest but didn't manage to find another solution. 

The issue is that the override changes the entity, hence we get a re-render of the model first when the override happens, then we send the transaction to Katana and it's executed and returns succesfully so we remove the override after Torii has updated so all is good. However sometimes Torii is a bit slow, so we remove the override before Torii registered that there is no building there. So we can a building that popups from a sec, then changes again when Torii is finallyupdated.

I've tried fiddling with stores, states and `useComponentValue` to no avail

**Closed by edisontim** 2024-05-30 14:40 UTC
