### ISSUE TITLE
I should be able to build the Cold Iron resource building....

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1652] opened 2024-09-18 09:46 UTC
I have the population and the one time cost-  I should be able to build it now? It seems like unless I have the consumable (cold iron) I can't build it, yet I have all the one off consumables

<img width="727" alt="image" src="https://github.com/user-attachments/assets/e75383c9-215d-45e7-8711-a0b0d33e1bbf">

**Comment by edisontim** [comment] 2024-09-18 14:31
Indeed, it's because you don't have enough Ironwood, either we need to make it clearer that you can't build or we should let build but it doesn't produce anything. @credence0x @ponderingdemocritus what do you guys think?

**Comment by credence0x** [comment] 2024-09-18 14:35
if you let them build, they are worse off because other resources start getting consumed immediately

**Comment by aymericdelab** [comment] 2024-09-18 20:56
marked as closed because this is intended behavior

**Closed by aymericdelab** 2024-09-18 20:56 UTC
