### ISSUE TITLE
[client] Cannot attack enemy army in ended battle

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#1330] opened 2024-08-20 13:17 UTC
ways to reproduce:

1. Battle between Realms A and B.
2. Realm A wins
3. Realm B leaves battle (Realm A army still in battle)
4. Try to attack Realm A army with Realm C: 'Battle' button is greyed out.

**Comment by edisontim** [comment] 2024-08-20 14:16
Couldn't reproduce but will leave open in case this happens again in the near future

**Comment by edisontim** [comment] 2024-08-21 20:08
Tried to reproduce a few times and couldn't, will close this

**Closed by edisontim** 2024-08-21 20:08 UTC
Labels: prio: high
